version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "scripts/requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r scripts/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "scripts/requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd scripts
            nosetests
